version: '3'
services:
    api:
        image: jeffstjean/enactushacks_nodejs
        env_file: .env
        ports:
            - "5000:5000"
        deploy:
            replicas: 3
            restart_policy: 
                max_attempts: 3
                condition: on-failure
            update_config:
                parallelism: 1
                delay: 10s
        networks:
            - app-network
    proxy:
        image: jeffstjean/enactushacks_nginx
        env_file: .env
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./proxy:/etc/nginx/
        deploy:
            placement:
                constraints: [node.role == manager]
        networks:
            - app-network
        depends_on: 
            - api

networks:
    app-network:
        driver: overlay