name: Build, Push and Deploy to Production Server

on:
    push:
        branches:
            - master

env:
    PROJECT_ID: ${{ secrets.GCE_PROJECT }}
    GCE_INSTANCE: ${{ secrets.GCE_INSTANCE_NAME }}
    GCE_INSTANCE_ZONE: ${{ secrets.GCE_INSTANCE_ZONE }}

jobs:
    setup-build-deploy:
        name: Build, Push and Deploy
        runs-on: ubuntu-latest

        steps:

        - name: Checkout
          uses: actions/checkout@v2 

        - name: Login to docker
          run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

        - name: Build api docker image
          run: docker build -t jeffstjean/enactushacks_nodejs ./api

        - name: Push api docker image
          run: docker push jeffstjean/enactushacks_nodejs

        - name: Deploy to remote server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.DEPLOY_HOST }}
            username: ${{ secrets.DEPLOY_USER }}
            key: ${{ secrets.DEPLOY_KEY }}
            script: docker stack deploy -c test/docker-compose.yml eh_prod

